const EVENTS = [
  
  /* ===== 2013 ===== */ 
  { year: "マジカルミライ2013", 
   shows: [ 
     { id:"2013_yokohama_0830_day", label:"横浜 8/30（金） 昼", songs:[
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    },
    { id: "2013_yokohama_0830_night", label: "横浜 8/30（金） 夜",
      songs: [
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 13, title: "Weekender Girl", vocalists: ["初音ミク"] },
        { order: 14, title: "FREELY TOMORROW", vocalists: ["初音ミク"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 23, title: "1/6 -out of the gravity-", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    }
  ]
},

/* ===== 2014 ===== */
{
  year: "マジカルミライ2014",
  shows: [
    {
      id: "2014_osaka_0830_day",
      label: "大阪 8/30（土） 昼",
      songs: [
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    },
    {
      id: "2014_osaka_0830_night",
      label: "大阪 8/30（土） 夜",
      songs: [
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    },
      {
      id: "2014_Tokyo_0920_day",
      label: "東京 9/20（土） 昼",
      songs: [
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 13, title: "Weekender Girl", vocalists: ["初音ミク"] },
        { order: 14, title: "FREELY TOMORROW", vocalists: ["初音ミク"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 23, title: "1/6 -out of the gravity-", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    },
      {
      id: "2014_Tokyo_0920_night",
      label: "東京 9/20（土） 夜",
      songs: [
        { order: 1, title: "Sweet Devil", vocalists: ["初音ミク"] },
        { order: 2, title: "二次元ドリーム フィーバー", vocalists: ["初音ミク"] },
        { order: 3, title: "キャットフード", vocalists: ["初音ミク"] },
        { order: 4, title: "からくりピエロ", vocalists: ["初音ミク"] },
        { order: 5, title: "ありふれたせかいせいふく", vocalists: ["初音ミク"] },
        { order: 6, title: "どうぶつ占い", vocalists: ["初音ミク"] },
        { order: 7, title: "深海少女", vocalists: ["初音ミク"] },
        { order: 8, title: "Hello, Worker", vocalists: ["巡音ルカ"] },
        { order: 9, title: "erase or zero", vocalists: ["KAITO","鏡音レン"] },
        { order: 10, title: "ピアノ×フォルテ×スキャンダル", vocalists: ["MEIKO"] },
        { order: 11, title: "スキキライ", vocalists: ["鏡音リン","鏡音レン"] },
        { order: 12, title: "shake it!", vocalists: ["初音ミク","鏡音リン","鏡音レン"] },
        { order: 13, title: "Weekender Girl", vocalists: ["初音ミク"] },
        { order: 14, title: "FREELY TOMORROW", vocalists: ["初音ミク"] },
        { order: 15, title: "Last Night, Good Night (Re:Dialed)", vocalists: ["初音ミク"] },
        { order: 16, title: "Leia", vocalists: ["巡音ルカ"] },
        { order: 17, title: "東京テディベア", vocalists: ["鏡音リン"] },
        { order: 18, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
        { order: 19, title: "glow", vocalists: ["初音ミク"] },
        { order: 20, title: "Tell Your World", vocalists: ["初音ミク"] },
        { order: 21, title: "39", vocalists: ["初音ミク"] },
        { order: 22, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
        { order: 23, title: "1/6 -out of the gravity-", vocalists: ["初音ミク"] },
        { order: 24, title: "ゆめゆめ", vocalists: ["初音ミク"] }
      ]
    }
  ]
},

/* ===== 2015 ===== */
{
  year: "マジカルミライ2015",
  shows: [
    { id:"2015_tokyo_0904_night", label:"東京 9/4（金） 夜", songs:[  { order: 1,  title: "Tell Your World", vocalists: ["初音ミク"] },
  { order: 2,  title: "ラズベリー＊モンスター", vocalists: ["初音ミク"] },
  { order: 3,  title: "はじめまして地球人さん", vocalists: ["初音ミク"] },
  { order: 4,  title: "独りんぼエンヴィー", vocalists: ["初音ミク"] },
  { order: 5,  title: "恋愛裁判", vocalists: ["初音ミク"] },
  { order: 6,  title: "聖槍爆裂ボーイ", vocalists: ["鏡音レン"] },
  { order: 7,  title: "ロストワンの号哭", vocalists: ["鏡音リン"] },
  { order: 8,  title: "リモコン", vocalists: ["鏡音リン", "鏡音レン"] },
  { order: 9,  title: "Nostalogic", vocalists: ["MEIKO"] },
  { order: 10, title: "スノーマン", vocalists: ["KAITO"] },
  { order: 11, title: "エンヴィキャットウォーク", vocalists: ["初音ミク"] },
  { order: 12, title: "深海少女", vocalists: ["初音ミク"] },
  { order: 13, title: "Sweet Devil", vocalists: ["初音ミク"] },
  { order: 14, title: "二次元ドリームフィーバー", vocalists: ["初音ミク"] },
  { order: 15, title: "キャットフード", vocalists: ["初音ミク"] },
  { order: 16, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
  { order: 17, title: "ロミオとシンデレラ", vocalists: ["初音ミク"] },
  { order: 18, title: "glow", vocalists: ["初音ミク"] },
  { order: 19, title: "愛Dee", vocalists: ["初音ミク", "巡音ルカ"] },
  { order: 20, title: "Just Be Friends", vocalists: ["巡音ルカ"] },
  { order: 21, title: "shake it!", vocalists: ["初音ミク", "鏡音リン", "鏡音レン"] },
  { order: 22, title: "Packaged", vocalists: ["初音ミク"] },
  { order: 23, title: "ワールドイズマイン", vocalists: ["初音ミク"] },
  { order: 24, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
  { order: 25, title: "Hand in Hand", vocalists: ["初音ミク"] },
  { order: 26, title: "39", vocalists: ["初音ミク"] },
  { order: 27, title: "ハジメテノオト", vocalists: ["初音ミク"] }] },
    { id:"2015_tokyo_0905_day", label:"東京 9/5（土） 昼", songs:[  { order: 1,  title: "Tell Your World", vocalists: ["初音ミク"] },
  { order: 2,  title: "ラズベリー＊モンスター", vocalists: ["初音ミク"] },
  { order: 3,  title: "はじめまして地球人さん", vocalists: ["初音ミク"] },
  { order: 4,  title: "独りんぼエンヴィー", vocalists: ["初音ミク"] },
  { order: 5,  title: "恋愛裁判", vocalists: ["初音ミク"] },
  { order: 6,  title: "聖槍爆裂ボーイ", vocalists: ["鏡音レン"] },
  { order: 7,  title: "ロストワンの号哭", vocalists: ["鏡音リン"] },
  { order: 8,  title: "リモコン", vocalists: ["鏡音リン", "鏡音レン"] },
  { order: 9,  title: "Nostalogic", vocalists: ["MEIKO"] },
  { order: 10, title: "スノーマン", vocalists: ["KAITO"] },
  { order: 11, title: "エンヴィキャットウォーク", vocalists: ["初音ミク"] },
  { order: 12, title: "深海少女", vocalists: ["初音ミク"] },
  { order: 13, title: "Sweet Devil", vocalists: ["初音ミク"] },
  { order: 14, title: "二次元ドリームフィーバー", vocalists: ["初音ミク"] },
  { order: 15, title: "キャットフード", vocalists: ["初音ミク"] },
  { order: 16, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
  { order: 17, title: "ロミオとシンデレラ", vocalists: ["初音ミク"] },
  { order: 18, title: "glow", vocalists: ["初音ミク"] },
  { order: 19, title: "愛Dee", vocalists: ["初音ミク", "巡音ルカ"] },
  { order: 20, title: "Just Be Friends", vocalists: ["巡音ルカ"] },
  { order: 21, title: "shake it!", vocalists: ["初音ミク", "鏡音リン", "鏡音レン"] },
  { order: 22, title: "Packaged", vocalists: ["初音ミク"] },
  { order: 23, title: "ワールドイズマイン", vocalists: ["初音ミク"] },
  { order: 24, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
  { order: 25, title: "Hand in Hand", vocalists: ["初音ミク"] },
  { order: 26, title: "39", vocalists: ["初音ミク"] },
  { order: 27, title: "ハジメテノオト", vocalists: ["初音ミク"] }] },
    { id:"2015_tokyo_0905_night", label:"東京 9/5（土） 夜", songs:[  { order: 1,  title: "Tell Your World", vocalists: ["初音ミク"] },
  { order: 2,  title: "ラズベリー＊モンスター", vocalists: ["初音ミク"] },
  { order: 3,  title: "はじめまして地球人さん", vocalists: ["初音ミク"] },
  { order: 4,  title: "独りんぼエンヴィー", vocalists: ["初音ミク"] },
  { order: 5,  title: "恋愛裁判", vocalists: ["初音ミク"] },
  { order: 6,  title: "聖槍爆裂ボーイ", vocalists: ["鏡音レン"] },
  { order: 7,  title: "ロストワンの号哭", vocalists: ["鏡音リン"] },
  { order: 8,  title: "リモコン", vocalists: ["鏡音リン", "鏡音レン"] },
  { order: 9,  title: "Nostalogic", vocalists: ["MEIKO"] },
  { order: 10, title: "スノーマン", vocalists: ["KAITO"] },
  { order: 11, title: "エンヴィキャットウォーク", vocalists: ["初音ミク"] },
  { order: 12, title: "深海少女", vocalists: ["初音ミク"] },
  { order: 13, title: "Sweet Devil", vocalists: ["初音ミク"] },
  { order: 14, title: "二次元ドリームフィーバー", vocalists: ["初音ミク"] },
  { order: 15, title: "キャットフード", vocalists: ["初音ミク"] },
  { order: 16, title: "アンハッピーリフレイン", vocalists: ["初音ミク"] },
  { order: 17, title: "ロミオとシンデレラ", vocalists: ["初音ミク"] },
  { order: 18, title: "glow", vocalists: ["初音ミク"] },
  { order: 19, title: "愛Dee", vocalists: ["初音ミク", "巡音ルカ"] },
  { order: 20, title: "Just Be Friends", vocalists: ["巡音ルカ"] },
  { order: 21, title: "shake it!", vocalists: ["初音ミク", "鏡音リン", "鏡音レン"] },
  { order: 22, title: "Packaged", vocalists: ["初音ミク"] },
  { order: 23, title: "ワールドイズマイン", vocalists: ["初音ミク"] },
  { order: 24, title: "ODDS&ENDS", vocalists: ["初音ミク"] },
  { order: 25, title: "Hand in Hand", vocalists: ["初音ミク"] },
  { order: 26, title: "39", vocalists: ["初音ミク"] },
  { order: 27, title: "ハジメテノオト", vocalists: ["初音ミク"] }] },
  ]
},

/* ===== 2016 ===== */
{
  year: "マジカルミライ2016",
  shows: [
    { id:"2016_tokyo_0909_night", label:"東京 9/9（金） 夜", songs:[ { "order": 1, "title": "39みゅーじっく！", "vocalists": ["初音ミク"] },
    { "order": 2, "title": "ゴーストルール", "vocalists": ["初音ミク"] },
    { "order": 3, "title": "ヒビカセ", "vocalists": ["初音ミク"] },
    { "order": 4, "title": "Strangers", "vocalists": ["初音ミク"] },
    { "order": 5, "title": "すろぉもぉしょん", "vocalists": ["初音ミク"] },
    { "order": 6, "title": "独りんぼエンヴィー", "vocalists": ["初音ミク"] },
    { "order": 7, "title": "タイムマシン", "vocalists": ["初音ミク"] },
    { "order": 8, "title": "Hello, Worker", "vocalists": ["巡音ルカ"] },
    { "order": 9, "title": "どりーみんチュチュ", "vocalists": ["巡音ルカ"] },
    { "order": 10, "title": "愛Dee", "vocalists": ["初音ミク", "巡音ルカ"] },
    { "order": 11, "title": "ドクター＝ファンクビート", "vocalists": ["KAITO"] },
    { "order": 12, "title": "Nostalogic (MEIKO-SAN mix)", "vocalists": ["MEIKO"] },
    { "order": 13, "title": "どうぶつ占い", "vocalists": ["初音ミク"] },
    { "order": 14, "title": "Calc.", "vocalists": ["初音ミク"] },
    { "order": 15, "title": "ウミユリ海底譚", "vocalists": ["初音ミク"] },
    { "order": 16, "title": "テレカクシ思春期", "vocalists": ["鏡音レン"] },
    { "order": 17, "title": "スイートマジック", "vocalists": ["鏡音リン"] },
    { "order": 18, "title": "リモコン", "vocalists": ["鏡音リン", "鏡音レン"] },
    { "order": 19, "title": "Baby Maniacs -Eight Mix-", "vocalists": ["初音ミク"] },
    { "order": 20, "title": "ラズベリー＊モンスター", "vocalists": ["初音ミク"] },
    { "order": 21, "title": "39", "vocalists": ["初音ミク"] },
    { "order": 22, "title": "shake it!", "vocalists": ["初音ミク", "鏡音リン", "鏡音レン"] },
    { "order": 23, "title": "ray", "vocalists": ["初音ミク"] },
    { "order": 24, "title": "Satisfaction", "vocalists": ["初音ミク"] },
    { "order": 25, "title": "なりすましゲンガー", "vocalists": ["鏡音リン", "初音ミク"] },
    { "order": 26, "title": "Hand in Hand", "vocalists": ["初音ミク"] }] },
    { id:"2016_tokyo_0910_day", label:"東京 9/10（土） 昼", songs:[ { "order": 1, "title": "39みゅーじっく！", "vocalists": ["初音ミク"] },
    { "order": 2, "title": "ゴーストルール", "vocalists": ["初音ミク"] },
    { "order": 3, "title": "ヒビカセ", "vocalists": ["初音ミク"] },
    { "order": 4, "title": "Strangers", "vocalists": ["初音ミク"] },
    { "order": 5, "title": "すろぉもぉしょん", "vocalists": ["初音ミク"] },
    { "order": 6, "title": "独りんぼエンヴィー", "vocalists": ["初音ミク"] },
    { "order": 7, "title": "タイムマシン", "vocalists": ["初音ミク"] },
    { "order": 8, "title": "Hello, Worker", "vocalists": ["巡音ルカ"] },
    { "order": 9, "title": "どりーみんチュチュ", "vocalists": ["巡音ルカ"] },
    { "order": 10, "title": "愛Dee", "vocalists": ["初音ミク", "巡音ルカ"] },
    { "order": 11, "title": "ドクター＝ファンクビート", "vocalists": ["KAITO"] },
    { "order": 12, "title": "Nostalogic (MEIKO-SAN mix)", "vocalists": ["MEIKO"] },
    { "order": 13, "title": "どうぶつ占い", "vocalists": ["初音ミク"] },
    { "order": 14, "title": "Calc.", "vocalists": ["初音ミク"] },
    { "order": 15, "title": "ウミユリ海底譚", "vocalists": ["初音ミク"] },
    { "order": 16, "title": "テレカクシ思春期", "vocalists": ["鏡音レン"] },
    { "order": 17, "title": "スイートマジック", "vocalists": ["鏡音リン"] },
    { "order": 18, "title": "リモコン", "vocalists": ["鏡音リン", "鏡音レン"] },
    { "order": 19, "title": "Baby Maniacs -Eight Mix-", "vocalists": ["初音ミク"] },
    { "order": 20, "title": "ラズベリー＊モンスター", "vocalists": ["初音ミク"] },
    { "order": 21, "title": "39", "vocalists": ["初音ミク"] },
    { "order": 22, "title": "shake it!", "vocalists": ["初音ミク", "鏡音リン", "鏡音レン"] },
    { "order": 23, "title": "ray", "vocalists": ["初音ミク"] },
    { "order": 24, "title": "Satisfaction", "vocalists": ["初音ミク"] },
    { "order": 25, "title": "なりすましゲンガー", "vocalists": ["鏡音リン", "初音ミク"] },
    { "order": 26, "title": "Hand in Hand", "vocalists": ["初音ミク"] }] },
    { id:"2016_tokyo_0910_night", label:"東京 9/10（土） 夜", songs:[ { "order": 1, "title": "39みゅーじっく！", "vocalists": ["初音ミク"] },
    { "order": 2, "title": "ゴーストルール", "vocalists": ["初音ミク"] },
    { "order": 3, "title": "ヒビカセ", "vocalists": ["初音ミク"] },
    { "order": 4, "title": "Strangers", "vocalists": ["初音ミク"] },
    { "order": 5, "title": "すろぉもぉしょん", "vocalists": ["初音ミク"] },
    { "order": 6, "title": "独りんぼエンヴィー", "vocalists": ["初音ミク"] },
    { "order": 7, "title": "タイムマシン", "vocalists": ["初音ミク"] },
    { "order": 8, "title": "Hello, Worker", "vocalists": ["巡音ルカ"] },
    { "order": 9, "title": "どりーみんチュチュ", "vocalists": ["巡音ルカ"] },
    { "order": 10, "title": "愛Dee", "vocalists": ["初音ミク", "巡音ルカ"] },
    { "order": 11, "title": "ドクター＝ファンクビート", "vocalists": ["KAITO"] },
    { "order": 12, "title": "Nostalogic (MEIKO-SAN mix)", "vocalists": ["MEIKO"] },
    { "order": 13, "title": "どうぶつ占い", "vocalists": ["初音ミク"] },
    { "order": 14, "title": "Calc.", "vocalists": ["初音ミク"] },
    { "order": 15, "title": "ウミユリ海底譚", "vocalists": ["初音ミク"] },
    { "order": 16, "title": "テレカクシ思春期", "vocalists": ["鏡音レン"] },
    { "order": 17, "title": "スイートマジック", "vocalists": ["鏡音リン"] },
    { "order": 18, "title": "リモコン", "vocalists": ["鏡音リン", "鏡音レン"] },
    { "order": 19, "title": "Baby Maniacs -Eight Mix-", "vocalists": ["初音ミク"] },
    { "order": 20, "title": "ラズベリー＊モンスター", "vocalists": ["初音ミク"] },
    { "order": 21, "title": "39", "vocalists": ["初音ミク"] },
    { "order": 22, "title": "shake it!", "vocalists": ["初音ミク", "鏡音リン", "鏡音レン"] },
    { "order": 23, "title": "ray", "vocalists": ["初音ミク"] },
    { "order": 24, "title": "Satisfaction", "vocalists": ["初音ミク"] },
    { "order": 25, "title": "なりすましゲンガー", "vocalists": ["鏡音リン", "初音ミク"] },
    { "order": 26, "title": "Hand in Hand", "vocalists": ["初音ミク"] }] },
    { id:"2016_tokyo_0911_day", label:"東京 9/11（日） 昼", songs:[ { "order": 1, "title": "39みゅーじっく！", "vocalists": ["初音ミク"] },
    { "order": 2, "title": "ゴーストルール", "vocalists": ["初音ミク"] },
    { "order": 3, "title": "ヒビカセ", "vocalists": ["初音ミク"] },
    { "order": 4, "title": "Strangers", "vocalists": ["初音ミク"] },
    { "order": 5, "title": "すろぉもぉしょん", "vocalists": ["初音ミク"] },
    { "order": 6, "title": "独りんぼエンヴィー", "vocalists": ["初音ミク"] },
    { "order": 7, "title": "タイムマシン", "vocalists": ["初音ミク"] },
    { "order": 8, "title": "Hello, Worker", "vocalists": ["巡音ルカ"] },
    { "order": 9, "title": "どりーみんチュチュ", "vocalists": ["巡音ルカ"] },
    { "order": 10, "title": "愛Dee", "vocalists": ["初音ミク", "巡音ルカ"] },
    { "order": 11, "title": "ドクター＝ファンクビート", "vocalists": ["KAITO"] },
    { "order": 12, "title": "Nostalogic (MEIKO-SAN mix)", "vocalists": ["MEIKO"] },
    { "order": 13, "title": "どうぶつ占い", "vocalists": ["初音ミク"] },
    { "order": 14, "title": "Calc.", "vocalists": ["初音ミク"] },
    { "order": 15, "title": "ウミユリ海底譚", "vocalists": ["初音ミク"] },
    { "order": 16, "title": "テレカクシ思春期", "vocalists": ["鏡音レン"] },
    { "order": 17, "title": "スイートマジック", "vocalists": ["鏡音リン"] },
    { "order": 18, "title": "リモコン", "vocalists": ["鏡音リン", "鏡音レン"] },
    { "order": 19, "title": "Baby Maniacs -Eight Mix-", "vocalists": ["初音ミク"] },
    { "order": 20, "title": "ラズベリー＊モンスター", "vocalists": ["初音ミク"] },
    { "order": 21, "title": "39", "vocalists": ["初音ミク"] },
    { "order": 22, "title": "shake it!", "vocalists": ["初音ミク", "鏡音リン", "鏡音レン"] },
    { "order": 23, "title": "ray", "vocalists": ["初音ミク"] },
    { "order": 24, "title": "Satisfaction", "vocalists": ["初音ミク"] },
    { "order": 25, "title": "なりすましゲンガー", "vocalists": ["鏡音リン", "初音ミク"] },
    { "order": 26, "title": "Hand in Hand", "vocalists": ["初音ミク"] }] }
  ]
},

/* ===== 2017 ===== */
{
  year: "マジカルミライ2017",
  shows: [
    { id:"2017_tokyo_0901_night", label:"東京 9/1（金） 夜", songs:[] },
    { id:"2017_tokyo_0902_day", label:"東京 9/2（土） 昼", songs:[] },
    { id:"2017_tokyo_0902_night", label:"東京 9/2（土） 夜", songs:[] },
    { id:"2017_tokyo_0903_day", label:"東京 9/3（日） 昼", songs:[] }
  ]
},

/* ===== 2018 ===== */
{
  year: "マジカルミライ2018",
  shows: [
    { id:"2018_osaka_0825_day", label:"大阪 8/25（土） 昼", songs:[] },
    { id:"2018_osaka_0825_night", label:"大阪 8/25（土） 夜", songs:[] },
    { id:"2018_osaka_0826_day", label:"大阪 8/26（日） 昼", songs:[] },
    { id:"2018_tokyo_0831_night", label:"東京 8/31（金） 夜", songs:[] },
    { id:"2018_tokyo_0901_day", label:"東京 9/1（土） 昼", songs:[] },
    { id:"2018_tokyo_0901_night", label:"東京 9/1（土） 夜", songs:[] },
    { id:"2018_tokyo_0902_day", label:"東京 9/2（日） 昼", songs:[] }
  ]
},

/* ===== 2019 ===== */
{
  year: "マジカルミライ2019",
  shows: [
    { id:"2019_osaka_0809_night", label:"大阪 8/9（金） 夜", songs:[] },
    { id:"2019_osaka_0810_day", label:"大阪 8/10（土） 昼", songs:[] },
    { id:"2019_osaka_0810_night", label:"大阪 8/10（土） 夜", songs:[] },
    { id:"2019_osaka_0811_day", label:"大阪 8/11（日） 昼", songs:[] },
    { id:"2019_tokyo_0830_night", label:"東京 8/30（金） 夜", songs:[] },
    { id:"2019_tokyo_0831_day", label:"東京 8/31（土） 昼", songs:[] },
    { id:"2019_tokyo_0831_night", label:"東京 8/31（土） 夜", songs:[] },
    { id:"2019_tokyo_0901_day", label:"東京 9/1（日） 昼", songs:[] }
  ]
},

/* ===== 2020 ===== */
{
  year: "マジカルミライ2020",
  shows: [
    { id:"2020_osaka_1127_night", label:"大阪 11/27（金） 夜", songs:[] },
    { id:"2020_osaka_1128_day", label:"大阪 11/28（土） 昼", songs:[] },
    { id:"2020_osaka_1128_night", label:"大阪 11/28（土） 夜", songs:[] },
    { id:"2020_osaka_1129_day", label:"大阪 11/29（日） 昼", songs:[] },
    { id:"2020_tokyo_1218_night", label:"東京 12/18（金） 夜", songs:[] },
    { id:"2020_tokyo_1219_day", label:"東京 12/19（土） 昼", songs:[] },
    { id:"2020_tokyo_1219_night", label:"東京 12/19（土） 夜", songs:[] },
    { id:"2020_tokyo_1220_day", label:"東京 12/20（日） 昼", songs:[] }
  ]
},

/* ===== 2021 ===== */
{
  year: "マジカルミライ2021",
  shows: [
    { id:"2021_osaka_1022_night", label:"大阪 10/22（金） 夜", songs:[] },
    { id:"2021_osaka_1023_day", label:"大阪 10/23（土） 昼", songs:[] },
    { id:"2021_osaka_1023_night", label:"大阪 10/23（土） 夜", songs:[] },
    { id:"2021_osaka_1024_day", label:"大阪 10/24（日） 昼", songs:[] },
    { id:"2021_tokyo_1105_night", label:"東京 11/5（金） 夜", songs:[] },
    { id:"2021_tokyo_1106_day", label:"東京 11/6（土） 昼", songs:[] },
    { id:"2021_tokyo_1106_night", label:"東京 11/6（土） 夜", songs:[] },
    { id:"2021_tokyo_1107_day", label:"東京 11/7（日） 昼", songs:[] }
  ]
},

/* ===== 2022 ===== */
{
  year: "マジカルミライ2022",
  shows: [
    { id:"2022_osaka_0812_night", label:"大阪 8/12（金） 夜", songs:[] },
    { id:"2022_osaka_0813_day", label:"大阪 8/13（土） 昼", songs:[] },
    { id:"2022_osaka_0813_night", label:"大阪 8/13（土） 夜", songs:[] },
    { id:"2022_osaka_0814_day", label:"大阪 8/14（日） 昼", songs:[] },
    { id:"2022_tokyo_0902_night", label:"東京 9/2（金） 夜", songs:[] },
    { id:"2022_tokyo_0903_day", label:"東京 9/3（土） 昼", songs:[] },
    { id:"2022_tokyo_0903_night", label:"東京 9/3（土） 夜", songs:[] },
    { id:"2022_tokyo_0904_day", label:"東京 9/4（日） 昼", songs:[] }
  ]
},

/* ===== 2023 ===== */
{
  year: "マジカルミライ2023",
  shows: [
    { id:"2023_osaka_0811_night", label:"大阪 8/11（金） 夜", songs:[] },
    { id:"2023_osaka_0812_day", label:"大阪 8/12（土） 昼", songs:[] },
    { id:"2023_osaka_0812_night", label:"大阪 8/12（土） 夜", songs:[] },
    { id:"2023_osaka_0813_day", label:"大阪 8/13（日） 昼", songs:[] },
    { id:"2023_tokyo_0901_night", label:"東京 9/1（金） 夜", songs:[] },
    { id:"2023_tokyo_0902_day", label:"東京 9/2（土） 昼", songs:[] },
    { id:"2023_tokyo_0902_night", label:"東京 9/2（土） 夜", songs:[] },
    { id:"2023_tokyo_0903_day", label:"東京 9/3（日） 昼", songs:[] }
  ]
},

/* ===== 2024 ===== */
{
  year: "マジカルミライ2024",
  shows: [
    { id:"2024_fukuoka_0817_day", label:"福岡 8/17（土） 昼", songs:[] },
    { id:"2024_fukuoka_0817_night", label:"福岡 8/17（土） 夜", songs:[] },
    { id:"2024_fukuoka_0818_day", label:"福岡 8/18（日） 昼", songs:[] },
    { id:"2024_tokyo_0830_night", label:"東京 8/30（金） 夜", songs:[] },
    { id:"2024_tokyo_0831_day", label:"東京 8/31（土） 昼", songs:[] },
    { id:"2024_tokyo_0831_night", label:"東京 8/31（土） 夜", songs:[] },
    { id:"2024_tokyo_0901_day", label:"東京 9/1（日） 昼", songs:[] },
    { id:"2024_osaka_1012_day", label:"大阪 10/12（土） 昼", songs:[] },
    { id:"2024_osaka_1012_night", label:"大阪 10/12（土） 夜", songs:[] },
    { id:"2024_osaka_1013_day", label:"大阪 10/13（日） 昼", songs:[] },
    { id:"2024_osaka_1014_day", label:"大阪 10/14（月祝） 昼", songs:[] }
  ]
},

/* ===== 2025 ===== */
{
  year: "マジカルミライ2025",
  shows: [
    { id:"2025_sendai_0801_night", label:"仙台 8/1（金） 夜", songs:[] },
    { id:"2025_sendai_0802_day", label:"仙台 8/2（土） 昼", songs:[] },
    { id:"2025_sendai_0802_night", label:"仙台 8/2（土） 夜", songs:[] },
    { id:"2025_sendai_0803_day", label:"仙台 8/3（日） 昼", songs:[] },
    { id:"2025_osaka_0809_day", label:"大阪 8/9（土） 昼", songs:[] },
    { id:"2025_osaka_0809_night", label:"大阪 8/9（土） 夜", songs:[] },
    { id:"2025_osaka_0810_day", label:"大阪 8/10（日） 昼", songs:[] },
    { id:"2025_osaka_0811_day", label:"大阪 8/11（月祝） 昼", songs:[] },
    { id:"2025_tokyo_0829_night", label:"東京 8/29（金） 夜", songs:[] },
    { id:"2025_tokyo_0830_day", label:"東京 8/30（土） 昼", songs:[] },
    { id:"2025_tokyo_0830_night", label:"東京 8/30（土） 夜", songs:[] },
    { id:"2025_tokyo_0831_day", label:"東京 8/31（日） 昼", songs:[] }
  ]
}

];
